name: vimdoc

on:
  push:
    branches:
      - main

jobs:
  genvimdoc:
    runs-on: [ubuntu-latest]
    name: generate vimdoc
    steps:
      - uses: actions/checkout@v2
      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: scratch-nvim

  updatedocs:
    permissions:
      contents: write
    steps:
      - uses: stefanzweifel/git-auto-commit-action@v4
      - name: update docs
        with:
          commit_message: "docs: auto generate docs"
          branch: ${{ github.head_ref }}
