name: vimdoc

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    name: gen vimdoc
    steps:
      - uses: actions/checkout@v2
      - uses: kdheepak/panvimdoc@main
        with:
          vimdoc: scratch-nvim
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs: update vimdoc"
          branch: ${{ github.head_ref }}
